api_url: "https://openlibrary.org/search.json"
default_query: "python"
default_limit: 50

data_paths:
  raw: "data/raw/"
  processed: "data/processed/"
  output: "data/output/"

logging_level: "INFO"
